name: Build NAPS2 Installers

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, macos-13]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3         
      with:
        dotnet-version: 6.0.x
        
    - name: Setup Xcode
      if: matrix.os == 'macos-13'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.3'

    - name: Install macos workload
      run: dotnet workload install macos

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish MacOS
      if: matrix.os == 'macos-13'
      run: dotnet run --project NAPS2.Tools -- publish -p mac pkg
    
    - name: Publish Windows
      if: matrix.os == 'windows-2022'
      run: dotnet run --project NAPS2.Tools -- publish -p win exe
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: principle-scan-manager-${{ matrix.os }}-artifacts
        path: NAPS2.Setup/publish/
