name: Build NAPS2 Installers

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-12]
        include:
          - os: windows-2022
            buildConfig: Release
            platform: Windows
            packageType: exe
          - os: windows-2022
            buildConfig: Release-Msi
            platform: Windows
            packageType: msi
          - os: ubuntu-22.04
            buildConfig: Release-Linux
            platform: Linux
            packageType: flatpak
          - os: macos-12
            buildConfig: Release
            platform: Mac
            packageType: dmg

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Install macos workload
      if: matrix.platform == 'Mac'
      run: dotnet workload install macos

    - name: Restore dependencies
      run: dotnet restore

    # Add platform-specific prerequisites installation here, like Inno Setup, WiX, Xcode, flatpak-builder, etc.

    - name: Build & Package
      run: |
        dotnet run --project NAPS2.Tools -- build ${{ matrix.buildConfig }} -v
        dotnet run --project NAPS2.Tools -- pkg ${{ matrix.packageType }}
    
    # Additional steps like uploading the built installer to GitHub releases or any storage can be added here.
